-- Add 3 sample patients
INSERT INTO `patient` (`id`, `version`, `created_at`, `updated_at`, `name`, `date_of_birth`)
VALUES
	(1, 0, '2019-02-21 15:25:14', '2019-02-21 15:25:14', 'Peter Gibbons', '1968-03-02'),
	(2, 0, '2019-02-21 15:27:03', '2019-02-21 15:27:03', 'Milton Waddams', '1954-12-14'),
	(3, 0, '2019-02-21 15:27:39', '2019-02-21 15:27:39', 'Bob Slydell', '1967-04-17');
	
-- Add clinician reviews for Patient 1
INSERT INTO `clinician_review` (`id`, `version`, `created_at`, `updated_at`, `patient`, `domain`, `clinician_priority`, `patient_readiness`, `referred`, `referral_complete`, `flagged`)
VALUES
	(1, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 1, 2, 3, 1, 0, 1),
	(2, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 2, 3, 1, 0, 0, 0),
	(3, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 3, 1, 3, 1, 0, 1),
	(4, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 4, 2, 2, 1, 0, 0),
	(5, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 5, 3, 1, 0, 0, 0),
	(6, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 6, 3, 1, 0, 0, 0),
	(7, 0, '2019-01-07 00:00:00', '2019-01-07 00:00:00', 1, 7, 1, 3, 1, 0, 1);
	
INSERT INTO `questionnaire_response` (`id`, `version`, `created_at`, `updated_at`, `patient`, `sdh_domain_questionnaire`, `answer_json`)
VALUES
	(1, 0, '2017-05-01 00:00:00', '2019-04-16 08:35:06', 1, 1, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford food when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(2, 0, '2017-05-01 00:00:00', '2019-04-16 08:35:16', 1, 2, '[{\"number\":1,\"text\":\"Has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living? Check all that apply.\",\"answers\":[\"Yes, it has kept me from medical appointments or from getting my medications.\",\"Yes, it has kept me from non-medical meetings, appointments, work, or from getting things that I need.\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(3, 0, '2017-05-01 00:00:00', '2019-04-16 08:35:25', 1, 3, '[{\"number\":1,\"text\":\"What is your housing situation today?\",\"answers\":[\"I have housing\",\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\",\"I choose not to answer this question\"],\"answer\":\"I have housing\"},{\"number\":2,\"text\":\"Are you worried about losing your housing?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(4, 0, '2017-05-01 00:00:00', '2019-04-16 08:35:44', 1, 4, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford any housing utilities (electricity, gas, etc) when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(5, 0, '2017-05-01 00:00:00', '2019-04-16 08:35:52', 1, 5, '[{\"number\":1,\"text\":\"Do you feel physically and emotionally safe where you currently live?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I choose not to answer this question\"],\"answer\":\"Yes\"},{\"number\":2,\"text\":\"In the past year, have you been afraid of your partner or ex-partner?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I have not had a partner in the past year\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(6, 0, '2017-05-01 00:00:00', '2019-04-16 08:38:56', 1, 6, '[{\"number\":1,\"text\":\"REALM-SF Score\",\"answers\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"answer\":\"7\"}]'),
	(7, 0, '2017-05-01 00:00:00', '2019-04-16 08:39:34', 1, 7, '[{\"number\":1,\"text\":\"What is your current work situation?\",\"answers\":[\"Unemployed\",\"Part-time or temporary work\",\"Full-time work\",\"Otherwise unemployed but not seeking work (ex: student, retired, disabled, unpaid primary care giver)\",\"I choose not to answer this question\"],\"answer\":\"Full-time work\"},{\"number\":2,\"text\":\"What is your main insurance?\",\"answers\":[\"None/uninsured\",\"Medicaid\",\"CHIP Medicaid\",\"Medicare\",\"Other public insurance (not CHIP)\",\"Other Public Insurance (CHIP)\",\"Private Insurance\"],\"answer\":\"Private Insurance\"},{\"number\":3,\"text\":\"During the past year, what was the total combined income for you and the family members you live with? This information will help us determine if you are eligible for any benefits\",\"answers\":[\"Under $20,000\",\"Between $20,000 and $40,000\",\"Between $40,000 and $60,000\",\"Over $60,000\",\"I choose not to answer this question\"],\"answer\":\"Between $40,000 and $60,000\"}]'),
	(8, 0, '2018-02-19 00:00:00', '2019-04-16 08:45:08', 1, 1, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford food when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(9, 0, '2018-02-19 00:00:00', '2019-04-16 08:45:19', 1, 2, '[{\"number\":1,\"text\":\"Has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living? Check all that apply.\",\"answers\":[\"Yes, it has kept me from medical appointments or from getting my medications.\",\"Yes, it has kept me from non-medical meetings, appointments, work, or from getting things that I need.\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(10, 0, '2018-02-19 00:00:00', '2019-04-16 08:45:29', 1, 3, '[{\"number\":1,\"text\":\"What is your housing situation today?\",\"answers\":[\"I have housing\",\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\",\"I choose not to answer this question\"],\"answer\":\"I have housing\"},{\"number\":2,\"text\":\"Are you worried about losing your housing?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(11, 0, '2018-02-19 00:00:00', '2019-04-16 08:45:36', 1, 4, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford any housing utilities (electricity, gas, etc) when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(12, 0, '2018-02-19 00:00:00', '2019-04-16 08:45:47', 1, 5, '[{\"number\":1,\"text\":\"Do you feel physically and emotionally safe where you currently live?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I choose not to answer this question\"],\"answer\":\"Yes\"},{\"number\":2,\"text\":\"In the past year, have you been afraid of your partner or ex-partner?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I have not had a partner in the past year\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(13, 0, '2018-02-19 00:00:00', '2019-04-16 08:46:13', 1, 6, '[{\"number\":1,\"text\":\"REALM-SF Score\",\"answers\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"answer\":\"7\"}]'),
	(14, 0, '2018-02-19 00:00:00', '2019-04-16 08:46:11', 1, 7, '[{\"number\":1,\"text\":\"What is your current work situation?\",\"answers\":[\"Unemployed\",\"Part-time or temporary work\",\"Full-time work\",\"Otherwise unemployed but not seeking work (ex: student, retired, disabled, unpaid primary care giver)\",\"I choose not to answer this question\"],\"answer\":\"Full-time work\"},{\"number\":2,\"text\":\"What is your main insurance?\",\"answers\":[\"None/uninsured\",\"Medicaid\",\"CHIP Medicaid\",\"Medicare\",\"Other public insurance (not CHIP)\",\"Other Public Insurance (CHIP)\",\"Private Insurance\"],\"answer\":\"Private Insurance\"},{\"number\":3,\"text\":\"During the past year, what was the total combined income for you and the family members you live with? This information will help us determine if you are eligible for any benefits\",\"answers\":[\"Under $20,000\",\"Between $20,000 and $40,000\",\"Between $40,000 and $60,000\",\"Over $60,000\",\"I choose not to answer this question\"],\"answer\":\"Between $40,000 and $60,000\"}]'),
	(15, 0, '2019-01-07 00:00:00', '2019-04-16 08:48:25', 1, 1, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford food when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(16, 0, '2019-01-07 00:00:00', '2019-04-16 08:48:41', 1, 2, '[{\"number\":1,\"text\":\"Has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living? Check all that apply.\",\"answers\":[\"Yes, it has kept me from medical appointments or from getting my medications.\",\"Yes, it has kept me from non-medical meetings, appointments, work, or from getting things that I need.\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(17, 0, '2019-01-07 00:00:00', '2019-04-16 08:48:53', 1, 3, '[{\"number\":1,\"text\":\"What is your housing situation today?\",\"answers\":[\"I have housing\",\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\",\"I choose not to answer this question\"],\"answer\":\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\"},{\"number\":2,\"text\":\"Are you worried about losing your housing?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"I choose not to answer this question\"}]'),
	(18, 0, '2019-01-07 00:00:00', '2019-04-16 08:49:10', 1, 4, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford any housing utilities (electricity, gas, etc) when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(19, 0, '2019-01-07 00:00:00', '2019-04-16 08:49:18', 1, 5, '[{\"number\":1,\"text\":\"Do you feel physically and emotionally safe where you currently live?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I choose not to answer this question\"],\"answer\":\"Yes\"},{\"number\":2,\"text\":\"In the past year, have you been afraid of your partner or ex-partner?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I have not had a partner in the past year\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(20, 0, '2019-01-07 00:00:00', '2019-04-16 08:49:48', 1, 6, '[{\"number\":1,\"text\":\"REALM-SF Score\",\"answers\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"answer\":\"7\"}]'),
	(21, 0, '2019-01-07 00:00:00', '2019-04-16 08:50:02', 1, 7, '[{\"number\":1,\"text\":\"What is your current work situation?\",\"answers\":[\"Unemployed\",\"Part-time or temporary work\",\"Full-time work\",\"Otherwise unemployed but not seeking work (ex: student, retired, disabled, unpaid primary care giver)\",\"I choose not to answer this question\"],\"answer\":\"Unemployed\"},{\"number\":2,\"text\":\"What is your main insurance?\",\"answers\":[\"None/uninsured\",\"Medicaid\",\"CHIP Medicaid\",\"Medicare\",\"Other public insurance (not CHIP)\",\"Other Public Insurance (CHIP)\",\"Private Insurance\"],\"answer\":\"None/uninsured\"},{\"number\":3,\"text\":\"During the past year, what was the total combined income for you and the family members you live with? This information will help us determine if you are eligible for any benefits\",\"answers\":[\"Under $20,000\",\"Between $20,000 and $40,000\",\"Between $40,000 and $60,000\",\"Over $60,000\",\"I choose not to answer this question\"],\"answer\":\"Between $40,000 and $60,000\"}]'),
	(22, 0, '2019-04-16 08:51:30', '2019-04-16 08:51:30', 1, 1, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford food when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"Yes\"}]'),
	(23, 0, '2019-04-16 08:52:01', '2019-04-16 08:52:01', 1, 2, '[{\"number\":1,\"text\":\"Has lack of transportation kept you from medical appointments, meetings, work, or from getting things needed for daily living? Check all that apply.\",\"answers\":[\"Yes, it has kept me from medical appointments or from getting my medications.\",\"Yes, it has kept me from non-medical meetings, appointments, work, or from getting things that I need.\",\"No\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(24, 0, '2019-04-16 08:52:11', '2019-04-16 08:52:11', 1, 3, '[{\"number\":1,\"text\":\"What is your housing situation today?\",\"answers\":[\"I have housing\",\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\",\"I choose not to answer this question\"],\"answer\":\"I do not have housing (staying with others, in a hotel, in a shelter, living outside on the street, on a beach, in a car, or in a park)\"},{\"number\":2,\"text\":\"Are you worried about losing your housing?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"I choose not to answer this question\"}]'),
	(25, 0, '2019-04-16 08:52:30', '2019-04-16 08:52:30', 1, 4, '[{\"number\":1,\"text\":\"In the past year, have you or any family members you live with been unable to get/afford any housing utilities (electricity, gas, etc) when it was really needed?\",\"answers\":[\"Yes\",\"No\",\"I choose not to answer this question\"],\"answer\":\"Yes\"}]'),
	(26, 0, '2019-04-16 08:52:40', '2019-04-16 08:52:40', 1, 5, '[{\"number\":1,\"text\":\"Do you feel physically and emotionally safe where you currently live?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I choose not to answer this question\"],\"answer\":\"Yes\"},{\"number\":2,\"text\":\"In the past year, have you been afraid of your partner or ex-partner?\",\"answers\":[\"Yes\",\"No\",\"Unsure\",\"I have not had a partner in the past year\",\"I choose not to answer this question\"],\"answer\":\"No\"}]'),
	(27, 0, '2019-04-16 08:53:02', '2019-04-16 08:53:02', 1, 6, '[{\"number\":1,\"text\":\"REALM-SF Score\",\"answers\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"answer\":\"7\"}]'),
	(28, 0, '2019-04-16 08:53:13', '2019-04-16 08:53:13', 1, 7, '[{\"number\":1,\"text\":\"What is your current work situation?\",\"answers\":[\"Unemployed\",\"Part-time or temporary work\",\"Full-time work\",\"Otherwise unemployed but not seeking work (ex: student, retired, disabled, unpaid primary care giver)\",\"I choose not to answer this question\"],\"answer\":\"Unemployed\"},{\"number\":2,\"text\":\"What is your main insurance?\",\"answers\":[\"None/uninsured\",\"Medicaid\",\"CHIP Medicaid\",\"Medicare\",\"Other public insurance (not CHIP)\",\"Other Public Insurance (CHIP)\",\"Private Insurance\"],\"answer\":\"Medicaid\"},{\"number\":3,\"text\":\"During the past year, what was the total combined income for you and the family members you live with? This information will help us determine if you are eligible for any benefits\",\"answers\":[\"Under $20,000\",\"Between $20,000 and $40,000\",\"Between $40,000 and $60,000\",\"Over $60,000\",\"I choose not to answer this question\"],\"answer\":\"I choose not to answer this question\"}]');

UPDATE `questionnaire_response` SET `wants_help`=1, `comments` = 'Peter states that because he lost his construction job, he is unable to afford his rent and has been living in his van as a result.' where id = 17;
UPDATE `questionnaire_response` SET `comments`= 'Peter states that he is trying to get disability benefits, and doesn’t feel he needs or would benefit from a referral regarding his financial strain.' where id = 21;
UPDATE `questionnaire_response` SET `wants_help`=1 where id = 22;
UPDATE `questionnaire_response` SET `wants_help`=1 where id = 25;
UPDATE `questionnaire_response` SET `wants_help`=1 where id = 28;

